### ISSUE TITLE
Prometheus alerting that service is down even though data can be read

### ISSUE THREAD

**Issue by JohSchillerEmnify** [tg44/OctoPrint-Prometheus-Exporter#20]
My setup is as follows:

## octoprint
```
version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 5000:80
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    volumes:
      - octoprint:/octoprint
      - ./docker/octoprint_data:/root/.octoprint/
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    environment:
      - ENABLE_MJPG_STREAMER=true
```
## Prometheus scrape config

``` 
  - job_name: 'octoprint'
    scrape_interval: 5s
    metrics_path: '/plugin/prometheus_exporter/metrics'
    params:
      apikey: ['__myapikey__']
    static_configs:
      - targets: ['octoprint:80']
```
even though I have tried  it without api key, and the scrape target (htttp://ipofoctoprintserver:portofoctoprintserver/plugin/prometheus_exporter/metrics)  is reachable and seems to display correct data. 

I have also tried to change the `static_configs: target`:

- `octoprint_octoprint_1:5000` (the container name I get from running docker ps and the port I configured)
- `127.0.0.1:5000` (reachable and displaying correct data)
- `octoprint:5000` 
 
all this still results in this:
![](https://i.imgur.com/s9xIJ9O.png)

unfortunately i'm not sure how to look for issues, I'm happy to provide any necessary data needed and help fixing this if I find a solution.
I am running a Prometheus/grafana Setup within a docker-container.

## UPDATE
I have looked into this further and have now tried pinging the docker container running Prometheus from the Container running Octoprint, this is possible, I have also noticed that the Prometheus/grafana Stack is running inside a seperate custom bridged network and joined the Octoprint container to that Network as well. Not sure where else to look.
